RndBoxPostBundle:
    resource: "@RndBoxPostBundle/Resources/config/routing.yml"
    prefix:   /

RndBoxAuthBundle:
    resource: "@RndBoxAuthBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
