RndBoxAuthBundle_home:
    pattern: /login
    defaults: { _controller: RndBoxAuthBundle:default:index }
RndBoxAuthBundle_registration:
    pattern: /signup
    defaults: { _controller: RndBoxAuthBundle:default:registration }



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
