RndBoxAuthBundle_home:
    pattern: /auth/login
    defaults: { _controller: RndBoxAuthBundle:Default:index }
RndBoxAuthBundle_registration:
    pattern: /auth/signup
    defaults: { _controller: RndBoxAuthBundle:Default:registration }

RndBoxAuthBundle_success:
    pattern: /auth/success
    defaults: { _controller: RndBoxAuthBundle:Default:success }
 


# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
